# Vocabulary files that were just created
src_vocab: output/vocab.src
tgt_vocab: output/vocab.tgt

# Train on a single GPU
world_size: 1
#gpu_ranks: [0]

# Where to save the checkpoints
save_model: output/model
save_checkpoint_steps: 500
train_steps: 1000
valid_steps: 500
